"""
HTML report generation — Python equivalent of New-TenantHtmlReport.
Uses Jinja2 for templating.
"""

from __future__ import annotations

import logging
from pathlib import Path

from jinja2 import Environment, BaseLoader

from ..snapshot import get_data, get_metadata

log = logging.getLogger(__name__)

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>M365 Tenant Assessment — {{ tenant_name }}</title>
<style>
  body { font-family: Segoe UI, Arial, sans-serif; margin: 0; padding: 0; background: #f5f5f5; color: #222; }
  header { background: #1f3864; color: #fff; padding: 24px 32px; }
  header h1 { margin: 0 0 4px; font-size: 1.6rem; }
  header p  { margin: 0; font-size: 0.9rem; opacity: .75; }
  main { max-width: 1200px; margin: 24px auto; padding: 0 24px; }
  section { background: #fff; border-radius: 6px; margin-bottom: 24px;
            box-shadow: 0 1px 4px rgba(0,0,0,.12); overflow: hidden; }
  section h2 { margin: 0; padding: 14px 20px; background: #1f3864;
               color: #fff; font-size: 1rem; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
  thead th { background: #d9e1f2; text-align: left; padding: 8px 12px;
             font-weight: 600; border-bottom: 2px solid #b0bfdf; }
  tbody tr:nth-child(even) { background: #f2f5fb; }
  td { padding: 6px 12px; border-bottom: 1px solid #e8eaf0; word-break: break-word; }
  .empty { padding: 16px 20px; color: #777; font-style: italic; }
  footer { text-align: center; color: #999; font-size: 0.78rem; padding: 24px; }
</style>
</head>
<body>
<header>
  <h1>Microsoft 365 Tenant Assessment</h1>
  <p>{{ tenant_name }} &nbsp;&bull;&nbsp; Generated {{ generated_at }}</p>
</header>
<main>
{% for section_name, tables in sections.items() %}
<section>
  <h2>{{ section_name }}</h2>
  {% for table_name, rows in tables.items() %}
  <h3 style="padding: 12px 20px 4px; margin: 0; font-size: .9rem; color: #444;">{{ table_name }}</h3>
  {% if rows %}
  <table>
    <thead>
      <tr>{% for col in rows[0].keys() %}<th>{{ col }}</th>{% endfor %}</tr>
    </thead>
    <tbody>
    {% for row in rows %}
      <tr>{% for v in row.values() %}<td>{{ v if v is not none else "" }}</td>{% endfor %}</tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="empty">No data collected.</p>
  {% endif %}
  {% endfor %}
</section>
{% endfor %}
</main>
<footer>Generated by Arraya M365 Assessment Toolkit</footer>
</body>
</html>"""


def generate(snapshot: dict, output_path: str | Path) -> None:
    output_path = Path(output_path)
    if output_path.suffix.lower() != ".html":
        output_path = output_path.with_suffix(".html")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    meta = get_metadata(snapshot)
    tenant_name = (
        meta.get("TenantDisplayName")
        or meta.get("TenantDomain")
        or "Unknown Tenant"
    )
    generated_at = meta.get("GeneratedAt", "")

    sections: dict[str, dict[str, list[dict]]] = {}
    data = get_data(snapshot)
    for section, tables in data.items():
        if not isinstance(tables, dict):
            continue
        section_tables: dict[str, list[dict]] = {}
        for table_name, rows in tables.items():
            if isinstance(rows, list):
                section_tables[table_name] = [
                    {str(k): v for k, v in (r.items() if isinstance(r, dict) else {})} for r in rows
                ]
            elif isinstance(rows, dict):
                section_tables[table_name] = [rows]
        if section_tables:
            sections[section] = section_tables

    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_TEMPLATE)
    html = tmpl.render(
        tenant_name=tenant_name,
        generated_at=generated_at,
        sections=sections,
    )

    output_path.write_text(html, encoding="utf-8")
    log.info("HTML report saved: %s", output_path)
